### ISSUE TITLE
+ eduardo's dashboard to each location page

### ISSUE THREAD

**Issue by 7yl4r** [marinebon/p2p#11]
Adding @diodon 's [p2p dashboard](diodon/p2p) to each location page would add a lot of interesting content.
Travis should be able to rebuild & deploy the dashboard as a static website.

* [ ] add run RS_dataTransform_3.Rmd to travis to generate the dashboard html
* [ ] need to upload data files (or get them from gdrive?)
* [ ] add a webshot to each location page which links to dashboard html for the location

Additional TODOs:
* [ ] migrate diodon/p2p into marinebon
* [ ] cleanup dashboard code

More info in [P2P Website Notes gdoc](https://docs.google.com/document/d/1fyPthk8RWni_O8HNSIu4JjxjLnL9nJratykljqE-Zhk/edit#bookmark=id.9x0npop864xs)

**Comment by diodon** [comment]
One issue is that until the data is not public we cannot expose it in github. The dashboard need a set of data files to produce the output.
Is there any way to have the data in a non-public repo and access it privately while building the dashboard?

**Comment by 7yl4r** [comment]
Yes, there are ways to do this. 
The files are in google drive right now, correct? 
If that is where people are comfortable putting them we can connect to google drive using a private API key stored in the travis settings.

@bbest : didn't you do this before? I know it is possible but I haven't done this with google drive.
