### ISSUE TITLE
Sites w no ts data

### ISSUE THREAD

**Issue by eqmh** [marinebon/p2p#16]
Hey @bbest, @7yl4r,

There is a list of sites that don't show SST and/or CHL time series plots possibly because of atmospheric correction issues since these sites are on land:

[sst_chl-arg-mardelplata-playachica.csv](https://marinebon.github.io/p2p/z_arg-mardelplata-playachica.html)
[sst_arg-mardelplata-saneduardob](https://marinebon.github.io/p2p/z_arg-mardelplata-saneduardobeach.html)
[sst_bra-arraialdocabo-fortaleza.csv](https://marinebon.github.io/p2p/z_bra-arraialdocabo-fortaleza.html)
[sst_bra-arraialdocabo-prainha.csv](https://marinebon.github.io/p2p/z_bra-arraialdocabo-prainha.html)
[sst_chl-bahiadevalparaiso-montemar.csv](https://marinebon.github.io/p2p/z_chl-bahiadevalparaiso-montemar.html)
[sst-concepcion-cocholguenorte.csv](https://marinebon.github.io/p2p/z_chl-concepcion-cocholguenorte.html)
[sst-concepcion-cocholguesur.csv](https://marinebon.github.io/p2p/z_chl-concepcion-cocholguesur.html)
[sst-concepcion-dichato-coliumo.csv](https://marinebon.github.io/p2p/z_chl-concepcion-dichato-coliumo.html)
[sst-puntaarenas-bahiamansa.csv](https://marinebon.github.io/p2p/z_chl-puntaarenas-bahiamansa.html)
[sst_cri-esmeralda.csv](https://marinebon.github.io/p2p/z_cri-esmeralda.html)
[sst_cri-sanmiguel.csv](https://marinebon.github.io/p2p/z_cri-sanmiguel.html)
[sst_mex-yucatan-marinadeyucalpeten.csv](https://marinebon.github.io/p2p/z_mex-yucatan-marinadeyucalpeten.html)
[sst_chl-ury-barradelchuy.csv](https://marinebon.github.io/p2p/z_ury-barradelchuy.html)
[sst_chl_usa-chesapeakebay.csv](https://marinebon.github.io/p2p/z_usa-chesapeakebay.html)
[sst_usa-hamiltoncove-lubecme.csv](https://marinebon.github.io/p2p/z_usa-hamiltoncove-lubecme.html)
[sst_usa-pumphouse-nahantma.csv](https://marinebon.github.io/p2p/z_usa-pumphouse-nahantma.html)

We have talked about a couple of solutions:
- Extracting values from a box and calculating the mean (this is my preferred option)
- Selecting the nearest pixel.

Do you have a quick fix for this? 

Thanks!

**Comment by 7yl4r** [comment]
Some technical notes on this on #14 .
Both solutions have pros/cons and neither are *hard*, but my R-fu is pretty bad.

**Comment by bbest** [comment]
Let's close this issue and go with solution I just suggested in:

- [+ box w/ arithmetic mean to `get_timeseries()` · Issue #14 · marinebon/p2p](https://github.com/marinebon/p2p/issues/14)
