### ISSUE TITLE
create _travis.yml

### ISSUE THREAD

**Issue by 7yl4r** [marinebon/p2p#2]
The ultimate plan here is to get Travis CI to build the Rmd into html, right?

I am not exactly certain how to set up the _travis.yml to do that but have a rough idea. Have you done this on another repo, @bbest ? It would be great to see an example.

**Comment by 7yl4r** [comment]
Hey @eqmh : so I'm looking at the latest [travis build](https://travis-ci.org/marinebon/p2p) and it looks like the `Rscript -e 'sessionInfo()'` is throwing an error because of a missing `DESCRIPTION`. I don't know much about it because this is an `R` thing, but I copied the `.travis.yml` from [marinebon.github.io](https://github.com/marinebon/marinebon.github.io) so we might try copying more things over from there.

**Comment by 7yl4r** [comment]
Yep, that got us to the next step. Now it is failing at the github push because of the auth token.

Now we just need to set up the github auth stuff explained in [these notes](https://gist.github.com/willprice/e07efd73fb7f13f917ea).

Not sure if that is in [travis-ci settings](https://travis-ci.org/marinebon/p2p/settings) or maybe something more complicated like [encryption keys](https://docs.travis-ci.com/user/encryption-keys/).

**Comment by bbest** [comment]
Yep, per [Encryption keys - Travis CI](https://docs.travis-ci.com/user/encryption-keys/), you'll need to install the travis Ruby command line to encrypt a variable on your local machine like:

```bash
# install Ruby command
gem install travis

# encrypt github password for upload
travis encrypt gh_passwd="secretvalue"
````

Check out this example: [setup Travis continuous integration (CI) to update daily · Issue #2 · SustainSB/sustainsb.github.io](https://github.com/SustainSB/sustainsb.github.io/issues/2)

**Comment by eqmh** [comment]
thanks, @bbest!

Just a quick note for future reference:
I got this message when installing travis: _You don't have write permissions for the /Library/Ruby/Gems/2.3.0 directory_

I solved this using:
sudo gem install travis (I found it [here](https://gist.github.com/jarun/df5d864f0b2600564c9bc13cfaca7497)) 

Just running _gem install travis_ was not working for me.

I got the key after running _travis encrypt SOMEVAR="secretvalue"_  and replaced the one that was in the .travis.yml.

I think we have a new set of issues with Travis.

**Comment by 7yl4r** [comment]
![xkcd#149](https://user-images.githubusercontent.com/1051390/48370031-1e1ca500-e686-11e8-8627-0be1572697cf.png)


The authentication is still failing in travis:

```
0.32s$ git push https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git HEAD:${TRAVIS_BRANCH}
remote: Anonymous access to marinebon/p2p.git denied.
fatal: Authentication failed for 'https://@github.com/marinebon/p2p.git/'
The command "git push https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git HEAD:${TRAVIS_BRANCH}" exited with 128.
```

Did you do literally `travis encrypt SOMEVAR="secretvalue"` or more like `travis encrypt GH_TOKEN="your_token_from_github"`? 
That long string in .travis.yml encrypts whatever string you give it and the string needs to set the `GH_TOKEN` variable.

**Comment by eqmh** [comment]
Travis CI seems to be working now. Closing this one out
