### ISSUE TITLE
Github Action commits with [ci skip] aren't being skipped by Travis CI; OR remove Travis CI?

### ISSUE THREAD

**Issue by 7yl4r** [marinebon/p2p#24]

**Comment by bbest** [comment]
@7yl4r, since we're updating with Github Actions, shouldn't we remove the Travis CI?

**Comment by 7yl4r** [comment]
Looks like you resolved this in f48b57d2e0f1ee7cf4590fe27b5726282f992e9c by removing travis. 👍 

Looking at the github actions I think that `[CI skip]` is used by those too so we want to keep it in the commit messages.
