### ISSUE TITLE
Add in situ temperature data from MARINe and p2p Gdrive

### ISSUE THREAD

**Issue by bbest** [marinebon/p2p#25]
This is being handled by:

* repository: [marinebon/intertidal-temps](https://github.com/marinebon/intertidal-temps)
  - issue: [#4 · prep MARINE sites for loading into marinebon.org/p2p](https://github.com/marinebon/intertidal-temps/issues/4)
  - issue: [#5 · prep gdata sites for loading into marinebon.org/p2p](https://github.com/marinebon/intertidal-temps/issues/5)

**Comment by bbest** [comment]
Hey @eqmh,

The EcoQuants intern Cristina @cdobbelaere and I added in situ temperature files here:

- [data/temperature_in-situ/](https://github.com/marinebon/p2p/tree/master/data/temperature_in-situ#in-situ-temperature-files)

There in the README.md, you can follow links to the updated site pages. Cristina will be revisiting the code to produce non-MARINe sites in situ temperature data from the p2p Gdrive that produced some initial odd results (see screenshots below).

## data/temperature_in-situ/README.md

### *In situ* Temperature Files

These files (*.csv, *.yml) were generated from MARINe and Pole to Pole data using code found in the Github repository [intertidal-temps](https://github.com/marinebon/intertidal-temps), and  more specifically [ingest.Rmd](https://github.com/marinebon/intertidal-temps/blob/main/ingest.Rmd) by Cristina Dobbelaere <CristinaDobbelaere@gmail.com> and Ben  Best <ben@ecoquants.com>.

**NOTE**: The sites that are not MARINe and in the P2P Google Drive folder still need to get checked and probably reproduced since the temperature values are oddly flat.

  - [Bentos - UFES](http://bentos.ufes.br/):
    [bra-costadasalgas-gramute](https://marinebon.org/p2p/z_bra-costadasalgas-gramute.html)
  - [IBIOMAR/CONICET](https://www.larbim.com.ar/):
    [arg-puertomadryn3](https://marinebon.org/p2p/z_arg-puertomadryn3.html)
  - [LECAR - UFF](http://www.lecar.uff.br/index.html):
    [bra-arraialdocabo-fortaleza](https://marinebon.org/p2p/z_bra-arraialdocabo-fortaleza.html)
  - [MARINe](https://marine.ucsc.edu/sitepages/bodega.html):
    [usa-bml](https://marinebon.org/p2p/z_usa-bml.html)
  - [MARINe](https://marine.ucsc.edu/sitepages/cambria.html):
    [usa-rmr](https://marinebon.org/p2p/z_usa-rmr.html)
  - [MARINe](https://marine.ucsc.edu/sitepages/hopkins.html):
    [usa-hop](https://marinebon.org/p2p/z_usa-hop.html)
  - [MARINe](https://marine.ucsc.edu/sitepages/piedrasblancas.html):
    [usa-pbl](https://marinebon.org/p2p/z_usa-pbl.html)
  - [S. Florida MBON](https://marinebon.org/pages/sfmbon/):
    [usa-fknms](https://marinebon.org/p2p/z_usa-fknms.html)

## Screenshot examples

### MARINe 👍 ✅ 
  - [MARINe](https://marine.ucsc.edu/sitepages/bodega.html):
    [usa-bml](https://marinebon.org/p2p/z_usa-bml.html)
    ![image](https://user-images.githubusercontent.com/2837257/116762263-bc279580-a9ce-11eb-9b0f-8f625b6d721c.png)

### non-MARINe 👎  ❎ 
   - [Bentos - UFES](http://bentos.ufes.br/):
    [bra-costadasalgas-gramute](https://marinebon.org/p2p/z_bra-costadasalgas-gramute.html)
    ![image](https://user-images.githubusercontent.com/2837257/116762294-d19cbf80-a9ce-11eb-81da-41f504941e14.png)

**Comment by bbest** [comment]
Hi  @cdobbelaere,

FYI I'm noticing some odd parsing errors suggesting inconsistent columns:

* Action [make_sites_monthly](https://github.com/marinebon/p2p/actions/workflows/make_sites_monthly.yml)
  * [make_sites_monthly.yml](https://github.com/marinebon/p2p/blob/master/.github/workflows/make_sites_monthly.yml)
    * [_site_template.Rmd](https://github.com/marinebon/p2p/blob/master/_site_template.Rmd)
      * [_temperature_in-situ.Rmd](https://github.com/marinebon/p2p/blob/master/_temperature_in-situ.Rmd)

https://github.com/marinebon/p2p/blob/e68110a1fa7bc9d226c8d4150939e127d78c119e/_temperature_in-situ.Rmd#L9

```
Warning: Warning: 5826 parsing failures.
 row       col           expected actual                                                              file
1480 Low       1/0/T/F/TRUE/FALSE  10.95 '/Users/runner/work/p2p/p2p/data/temperature_in-situ/usa-hop.csv'
1480 Lower-Mid 1/0/T/F/TRUE/FALSE  10.91 '/Users/runner/work/p2p/p2p/data/temperature_in-situ/usa-hop.csv'
...
Warning: Warning: 1672 parsing failures.
 row       col           expected actual                                                              file
1007 Upper-Mid 1/0/T/F/TRUE/FALSE  12.99 '/Users/runner/work/p2p/p2p/data/temperature_in-situ/usa-pbl.csv'
1008 Upper-Mid 1/0/T/F/TRUE/FALSE  12.99 '/Users/runner/work/p2p/p2p/data/temperature_in-situ/usa-pbl.csv'
...
Warning: Warning: 224 parsing failures.
 row       col           expected actual                                                              file
1269 Lower-Mid 1/0/T/F/TRUE/FALSE  26.64 '/Users/runner/work/p2p/p2p/data/temperature_in-situ/usa-rmr.csv'
1270 Lower-Mid 1/0/T/F/TRUE/FALSE  18.55 '/Users/runner/work/p2p/p2p/data/temperature_in-situ/usa-rmr.csv'
```

But those above are for the MARINe sites, not the problematic other ones.

**Comment by cdobbelaere** [comment]
Hi @bbest, Sorry for the late response! Looking into it now. I did fix the smoothing issue with the problematic p2p gdata sites.

**Comment by bbest** [comment]
Looking good now! Nicely done @cdobbelaere 🥳 

For example:

- [Site: Arraial do Cabo - Fortaleza](https://marinebon.org/p2p/z_bra-arraialdocabo-fortaleza.html)

## OLD non-MARINe 👎 ❎

![image](https://user-images.githubusercontent.com/2837257/117189898-8f3efe00-ad93-11eb-9ad5-62db66cc77dd.png)

## NEW non-MARINe 👍 ✅

![image](https://user-images.githubusercontent.com/2837257/117190023-bd244280-ad93-11eb-84f3-7f99451fcc4d.png)

**Comment by bbest** [comment]
With  commit: [+ "ºC" ylab to plot_dygraph() · marinebon/p2p@502a9af](https://github.com/marinebon/p2p/commit/502a9af8e2a79155095dcb19501040e26a5a5815)

## Improvement: added ºC to y-label

![image](https://user-images.githubusercontent.com/2837257/117191711-bc8cab80-ad95-11eb-84a1-7620c7fa2f97.png)

**Comment by bbest** [comment]
----
Hey Ben, Cristina,

Edgardo was able to pull the data from the loggers he installed in **Gorgona Island (Colombia)**. The 024537 is the _**sun**_-exposed logger and the 024444 is the _**shaded**_ one.  The loggers registered temperatures above 52 C.  
The files are also stored in the [GDrive](https://drive.google.com/drive/folders/1C40MZkitxp6KCt7am3yovOcJFzusVlXW?usp=sharing).
 
Let me know when we can meet with your intern at Caltech to look at these records. Edgardo, let me know if you would like to participate in the discussion about advancing this [tool](https://github.com/marinebon/intertidal-temps).

Cheers, Enrique

**Comment by bbest** [comment]
Hey @eqmh,


So @cdobbelaere and I got this going for [Gorgona Island (Colombia)](https://marinebon.org/p2p/z_col-islagorgona-laventana.html) with the new shading to min/max she also implemented for all other non-MARINe sites (see * [data/temperature_in-situ/*](https://github.com/marinebon/p2p/tree/master/data/temperature_in-situ) except [MARINe_sites.csv](https://github.com/marinebon/p2p/blob/master/data/temperature_in-situ/MARINe_sites.csv)):

![image](https://user-images.githubusercontent.com/2837257/119724241-54286b80-be23-11eb-8806-66567b899d39.png)

**Comment by eqmh** [comment]
Hi @bbest and @cdobbelaere,
Very cool! Glad to see this already up and running on the website. Great work, thanks!
Let's chat about automating the workflow to update these time series plots as new data becomes available.
