### ISSUE TITLE
Failed to get R 4.3.1 error 

### ISSUE THREAD

**Issue by eqmh** [marinebon/p2p#29]
@7yl4r and @bbest 

Github Actions is reporting this 404 after a push to modify web page content:
 
Failed to get R 4.3.1: Failed to get R 4.3.1: Failed to download version 4.3.1: Error: Unexpected HTTP response: 404

Do you know a quick fix for this?

**Comment by 7yl4r** [comment]
[Here](https://github.com/marinebon/p2p/actions/runs/6656550211/job/18089492790) is a link to the relevant log. 

Looks like "r-lib/actions/setup-r@v1 is deprecated". I'll try to update it.

**Comment by 7yl4r** [comment]
Looks like that fixed it.
