### ISSUE TITLE
implement alternate image storage

### ISSUE THREAD

**Issue by bbest** [marinebon/p2p#3]
Hi @eqmh,

We should figure out a different image storage strategy other than Github, which should be used for versioning code, not 1.2 GB of imagery (and we're just getting started). The individual repository limit is 10 GB.  This also adds a lot of bulk to the repository for files which don't need versioning and slows down the website editing process with the time-consuming pull (and push if including in output website).

I recommend we:

1. Transfer all the images in `survey imagery` into a shared album in Google Photos.

1. Permanently remove this folder from the repository and its history to reduce the repo's size:
    
    ```bash
    git filter-branch --tree-filter 'rm -rf "survey imagery"' HEAD
    ```
1. Embed gallery like so: [How do I embed a Google Photos album into a website? - Public album .org](https://www.publicalbum.org/blog/embedding-google-photos-albums)

PS Here's what I saw when first trying to pull repo with `1.22 GiB` to receive:

```
bbest$ git pull
remote: Enumerating objects: 16, done.
remote: Counting objects: 100% (16/16), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 504 (delta 11), reused 11 (delta 11), pack-reused 488
Receiving objects: 100% (504/504), 1.22 GiB | 960.00 KiB/s, done.
Resolving deltas: 100% (191/191), completed with 6 local objects.
From https://github.com/marinebon/p2p
   5f6f4ae..99f644a  master     -> origin/master
```

**Comment by 7yl4r** [comment]
I 2nd this approach. 

My only concern with google photos is potential data loss in the future if google accounts get lost or deleted. However, I do not know of a better (free) service to suggest for this. I use google photos for my personal photos and would recommend.

**Comment by 7yl4r** [comment]
It looks to me like the [latest failed travis build](https://travis-ci.org/marinebon/p2p/builds/454658238) may have stalled for this reason ( the build took >10min to clone).

@eqmh : Let me know once you get the photos moved into g-photos (or elsewhere) and I will help prune them from the git history tree.

**Comment by eqmh** [comment]
Hey @bbest, @7yl4r,

Removing imagery from the repo and adding the 'here' package fixed Travis CI bugs. Good call!

I am closing the Travis CI issue now. I will also move imagery into g-photos.
