### ISSUE TITLE
lazy-load database error on Events.Rmd

### ISSUE THREAD

**Issue by eqmh** [marinebon/p2p#5]
Hi @7yl4r , @bbest ,

I am making a very simple change to the Events.Rmd file: move **American Gephysical Union Fall Meeting 2018** to Past.

I get this error in Travis CI:

Error in get0(oNam, envir = ns) : 
  lazy-load database '/home/travis/R/Library/callr/R/callr.rdb' is corrupt
Calls: <Anonymous> ... force -> rcmd_build_tools -> :: -> getExportedValue -> get0
In addition: Warning message:
In get0(oNam, envir = ns) : internal error -3 in R_decompress1
Execution halted
The command "Rscript -e 'deps <- devtools::dev_package_deps(dependencies = NA);devtools::install_deps(dependencies = TRUE);if (!all(deps$package %in% installed.packages())) { message("missing: ", paste(setdiff(deps$package, installed.packages()), collapse=", ")); q(status = 1, save = "no")}'" failed and exited with 1 during .

There seems to be a issue with R. If this is trivial just let me know.

Thanks,
@eqmh

**Comment by 7yl4r** [comment]
Huh. That's a weird one. 
I have deleted the cache in travis (settings>cache>delete) and restarted the build.
Looks like it is passing now.

Just a temporary weird problem from a hiccup on the travis server I guess.

**Comment by eqmh** [comment]
Thanks, @7yl4r!
