### ISSUE TITLE
SST time series plot does not display

### ISSUE THREAD

**Issue by eqmh** [marinebon/p2p#7]
Hi @bbest, @7yl4r 

I updated the coords for the St Pete site (Pass-A-Grille) and everything ran fine except that the SST time series data were not generated for the new location. I think this is an issue with Travis CI:

![image](https://user-images.githubusercontent.com/20710865/53373678-2bebf280-3924-11e9-9c0d-bc9e14f11f8b.png)

![image](https://user-images.githubusercontent.com/20710865/53373788-71a8bb00-3924-11e9-94ad-d1e1eae30810.png)

I am wondering if I skipped a step here.

Many thanks,
Enrique

**Comment by bbest** [comment]
Hi @eqmh,

To get the SST timeseries data for the new location at [Site: Pass-a-Grille](https://marinebon.github.io/p2p/z_usa-usfstpete.html), you simply needed to delete the [data/sst/sst_usa-usfstpete.csv](https://github.com/marinebon/p2p/blob/master/data/sst/sst_usa-usfstpete.csv) file and regenerate.

I added the following to the README:

> - **WARNING**: If you change the coordinates of a site (ie lat/lon in `sites.csv`), please delete the associated site's file in `data/sst`, so the timeseries plot becomes representative of the data for that coordinate.

I like testing it out by setting parameters in the [site_template.Rmd](https://github.com/marinebon/p2p/blob/master/site_template.Rmd) and knitting, eg parameters:

```yaml
params:
  site_name: "Pass-a-Grille"
  site_id: "usa-usfstpete"
```

Now, you can see:

- Map of latest SST showing the marker over a valid SST (same as before)
  ![image](https://user-images.githubusercontent.com/2837257/53376195-6482d080-3912-11e9-8f70-558279ff04d9.png)

- Timeseries
  ![image](https://user-images.githubusercontent.com/2837257/53376444-2df98580-3913-11e9-9664-ef9106072be1.png)
